version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 40000:8000
    volumes:
      - .:/workspaces/flume-ledger:cached
    command: sleep infinity 