# Generated by Django 4.2.20 on 2025-08-29 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_inboundnonce_delete_inboundnounce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundNonceBootstrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(db_index=True, max_length=120)),
                ('nonce', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InboundServiceInstanceNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.CharField(db_index=True, max_length=64)),
                ('service_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='app.serviceinstance')),
            ],
        ),
        migrations.DeleteModel(
            name='InboundNonce',
        ),
        migrations.AddIndex(
            model_name='inboundnoncebootstrap',
            index=models.Index(fields=['created_at'], name='app_inbound_created_1012cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundnoncebootstrap',
            constraint=models.UniqueConstraint(fields=('service_name', 'nonce'), name='uniq_service_name_nonce'),
        ),
        migrations.AddIndex(
            model_name='inboundserviceinstancenonce',
            index=models.Index(fields=['created_at'], name='app_inbound_created_4476b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundserviceinstancenonce',
            constraint=models.UniqueConstraint(fields=('service_instance', 'nonce'), name='uniq_instance_nonce'),
        ),
    ]
